--EJERCICIO 1
INSERT INTO DEPART
VALUES (11, 'CALIDAD', 'SANTANDER');

SELECT * FROM DEPART;

INSERT INTO EMPLE
VALUES (7231, 'AGUIRRE', 'EMPLEADO', NULL, TO_DATE('24/11/2017','DD/MM/YYYY'), 5000, NULL,(SELECT DEPT_NO FROM DEPART
WHERE UPPER (DNOMBRE) = 'CALIDAD'));

SELECT * FROM EMPLE;

--EJERCICIO 2
UPDATE EMPLE
SET SALARIO = SALARIO - (SALARIO * 0.1);

SELECT * FROM EMPLE;

--EJERCICIO 3
UPDATE EMPLE
SET DEPT_NO = 40
WHERE DEPT_NO = 10;

SELECT * FROM EMPLE;

--EJERCICIO 4
UPDATE EMPLE
SET OFICIO = (SELECT EMP_NO FROM EMPLE WHERE UPPER(EMP_NO) = ('TOVAR'))
WHERE EMP_NO = (7556);

SELECT * FROM EMPLE;

--EJERCICIO 5
INSERT INTO EMPLE
VALUES (7245, 'MUÑOZ', 'EMPLEADO', NULL, TO_DATE('20/11/2017','DD/MM/YYYY'), 4000, NULL,(SELECT DEPT_NO FROM DEPART
WHERE UPPER (DNOMBRE) = 'CALIDAD'));

SELECT * FROM EMPLE;

UPDATE EMPLE
SET SALARIO = (SELECT SALARIO FROM EMPLE WHERE UPPER(APELLIDO) = ('MUÑOZ'))
WHERE OFICIO = ('EMPLEADO');

SELECT * FROM EMPLE;

--EJERCICIO 6
UPDATE EMPLE
SET SALARIO = SALARIO - 300
WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE LOC = ('SANTANDER'));

SELECT * FROM EMPLE;

--EJERCICIO 7
DELETE FROM DEPART
WHERE DEPT_NO = (30);

COMMIT;