CREATE TABLE Alumnos(

  DNI VARCHAR2(10) NOT NULL PRIMARY KEY,
  
  NOMBRE VARCHAR2(30) NOT NULL
  
    CHECK (UPPER(NOMBBRE) = NOMBRE),
  
  EDAD NUMBER(2)
  
    CONSTRAINT EDAD_min CHECK (EDAD >= 5)
    CONSTRAINT EDAD_max CHECK (EDAD <= 20),
  
  CURSO NUMBER(1)
  
    CONSTRAINT CURSO_min CHECK (CURSO > 0)
    CONSTRAINT CURSO_MAX CHECK (EDAD <= 3)
    
);